### ISSUE TITLE
Filterung entspricht nicht immer der Ansicht der Filterung auf block_course_overview_campus

### ISSUE THREAD

**Issue by sberger** [moodleuulm/moodle-local_boostcoc#2]
local_boostcoc | enablenotshown und local_boostcoc | disableinprogressfilter sind beide aktiviert (auf ja gestellt).

block_course_overview_campus | termcoursefilterdisplayname ist aktivert und auf 2 Zeitenräume (Semester) gestellt.

Trotzdem werden nicht immer alle Kurse angezeigt bei "Meine Kurse" im Navigationsbereich – siehe:
![bildschirmfoto 2018-09-05 um 11 34 44](https://user-images.githubusercontent.com/3737740/45084928-bedb6b00-b0ff-11e8-96e3-83970e61a71d.png)

Auf zwei Plattformen habe ich verschiedene Varianten probiert – immer gleiches Ergebnis – nur beim Admin scheint es immer richtig zu funktionieren, bei anderen normalen Nutzern gibt es Kurse die nicht angezeigt werden.

**Comment by abias** [comment]
Hi Stefanie,

sorry that it took me so long to come back to you to answer your question. And I hope that it's ok that I answer in english for others to understand what we are talking about here :)

Yes, in the Boost nav drawer, there might be a "More..." link at the bottom of the course list, leading to the Dashboard page if I remember correctly. I have the strong feeling that this is bad design, but this is how Moodle HQ has built it currently.

You can overcome this bad behavior generally (and especially when using local_boostcoc) by raising the number of courses to be displayed with the setting navcourselimit.
We have already covered this in the local_boostcoc README on https://github.com/moodleuulm/moodle-local_boostcoc#list-length.

If I misunderstood your problem, please don't hesitate to come back to me again.

Cheers,
Alex
